# generated by fastapi-codegen:
#   filename:  connector
#   timestamp: 2025-07-30T09:12:25+00:00

from __future__ import annotations

from typing import Optional
from fastapi.responses import JSONResponse

from src.centra_sdk.models.connector.version import VersionHandshakeData
from src.centra_sdk.routers.control import ControlHandler
from src.centra_sdk.main import  app
from src.centra_sdk.handler_registry import register
from fastapi.encoders import jsonable_encoder
import uvicorn


@register('Control')
class PartnerControl(ControlHandler):
    def version_hanshake(self, body: VersionHandshakeData) -> VersionHandshakeData:
        print(f'process handshake: {body}')
        return VersionHandshakeData(version='1',
                                    contract_version='2',
                                    component_id='3')


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
