# generated by fastapi-codegen:
#   filename:  connector
#   timestamp: 2025-07-30T09:12:25+00:00

from __future__ import annotations

from typing import Optional
from fastapi.responses import JSONResponse

from src.centra_sdk.models.connector.v1.consumer.enforcement import EnforcementPolicy, Action
from src.centra_sdk.routers.enforcement import EnforcementHandler
from src.centra_sdk.main import  app
from src.centra_sdk.handler_registry import register
import uvicorn


@register('Enforcement')
class PartnerEnforcement(EnforcementHandler):
    def set_enforcement_policy_handler(self,
                                       action: Optional[Action] = 'set',
                                       body: EnforcementPolicy = ...):
        print(f'process policy: {body}')
        return JSONResponse(status_code=200)


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
