# generated by fastapi-codegen:
#   filename:  connector
#   timestamp: 2025-07-29T18:35:05+00:00

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Optional, Union
from uuid import UUID

from fastapi import APIRouter
from fastapi.responses import JSONResponse
from pydantic import conint

from ..dependencies import *
from ..models.connector.v1.common.inventory import InventoryItem
from ..models.connector.v1.consumer.agents import AgentsInfo
from ..models.connector.v1.consumer.enforcement import (
    Action,
    EnforcementPolicy,
    EnforcementPolicyInventory,
)
from ..models.connector.v1.operations.config import (
    InternalConfig,
    InternalConfigMetadata,
)
from ..models.connector.v1.operations.health import (
    V1OperationsFlagsGetResponse,
    V1OperationsHealthGetResponse,
    V1OperationsMetricsGetResponse,
)
from ..models.connector.v1.operations.info import EnvUnits, IntegrationEnvInfo
from ..models.connector.v1.operations.log import LogStart, LogStatus
from ..models.connector.v1.operations.onboard import (
    Onboard,
    StatusRequest,
    StatusResponse,
)
from ..models.connector.v1.provider.inventory import (
    Inventory,
    InventoryAssetType,
    InventoryReporterType,
    Labels,
    NetworkTopology,
    V1ProviderInventoryIdAssetsAssetTypePostResponse,
    V1ProviderInventoryIdAssetsAssetTypePostResponse1,
)
from ..models.connector.v1.provider.lookup import LookupRequest
from ..models.connector.version import VersionHandshakeData

router = APIRouter(tags=['Enforcement'])


class EnforcementAPIController(ABC):
    def __init__(self):
        pass

    @abstractmethod
    def set_enforcement_policy_inventory_handler(
        self, action: Optional[Action] = 'set', body: EnforcementPolicyInventory = ...
    ) -> None:
        """This method should be implemented by the subclass."""
        return JSONResponse(status_code=404)

    @abstractmethod
    def set_enforcement_policy_handler(
        self, action: Optional[Action] = 'set', body: EnforcementPolicy = ...
    ) -> None:
        """This method should be implemented by the subclass."""
        return JSONResponse(status_code=404)

    @router.post('/v1/consumer/inventory', response_model=None, tags=['Enforcement'])
    def set_enforcement_policy_inventory(
        self, action: Optional[Action] = 'set', body: EnforcementPolicyInventory = ...
    ) -> None:
        """
        Set enforcement policy inventory
        """
        return self.set_enforcement_policy_inventory_handler(action, body)

    @router.post('/v1/consumer/policy', response_model=None, tags=['Enforcement'])
    def set_enforcement_policy(
        self, action: Optional[Action] = 'set', body: EnforcementPolicy = ...
    ) -> None:
        """
        Set enforcement policy
        """
        return self.set_enforcement_policy_handler(action, body)
