# generated by fastapi-codegen:
#   filename:  connector
#   timestamp: 2025-07-29T18:35:05+00:00

from __future__ import annotations

from fastapi import FastAPI

from .routers import control, enforcement, inventory, operations

app = FastAPI(
    title='Version Handshake API',
    version='1.0.0',
)

routers = {}
routers["control"] = control.router
routers["enforcement"] = enforcement.router
routers["inventory"] = inventory.router
routers["operations"] = operations.router


def init_routers(custom_routers):
    for tag, router in routers:
        if tag in custom_routers:
            print(f'use customer router for: {tag}')
            app.include_router(custom_routers[tag])
        else:
            app.include_router(router)


@app.get("/")
async def root():
    return {"message": "Gateway of the App"}
