# generated by fastapi-codegen:
#   filename:  connector
#   timestamp: 2025-07-29T18:35:05+00:00

from __future__ import annotations

from fastapi import FastAPI

from .routers import control, enforcement, inventory, operations

app = FastAPI(
    title='Version Handshake API',
    version='1.0.0',
)

app.include_router(control.router)
app.include_router(enforcement.router)
app.include_router(inventory.router)
app.include_router(operations.router)


@app.get("/")
async def root():
    return {"message": "Gateway of the App"}
